### ISSUE TITLE
博文录加载失败

### ISSUE THREAD

**Issue by nsdnsg** [SPXFellow/minecraft.net-translations#2]
rt，我的设备上显示博文录加载失败。
![Screenshot_2021-07-10-12-44-40-21_75859cd55dc75568249b155c65ccd4ec](https://user-images.githubusercontent.com/65689845/125151984-9eb83a00-e17c-11eb-900e-b7816425529e.jpg)
我的浏览器版本
![Screenshot_2021-07-10-12-45-39-70_75859cd55dc75568249b155c65ccd4ec](https://user-images.githubusercontent.com/65689845/125152030-cd361500-e17c-11eb-8de7-65c48f38144d.png)

**Comment by RicoloveFeng** [comment]
因为要请求 Github 的内容，如果没有代理可能没法获取博文录的内容。另，这个得在 SPX 的仓库发 issue。
